spring:
  session:
    jdbc:
      initialize-schema: never
  application:
    name: national-energy-platform

  datasource:
    url: jdbc:mysql://localhost:3306/national_energy_platform
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
  servlet:
    context-path: /national-energy-platform

  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always