spring:
  session:
    jdbc:
      initialize-schema: never
  application:
    name: national-energy-platform

  datasource:
    url: jdbc:mysql://localhost:3306/national_energy_platform
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: false

    properties:
      hibernate:
        format_sql: false

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 8080
  servlet:
    context-path: /national-energy-platform

  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

google:
  vision:
    api-key: ${GOOGLE_VISION_API_KEY}
    endpoint: https://vision.googleapis.com/v1/images:annotate